# modules/home-manager/hyprland/default.nix
#
# User-level Hyprland configuration, split into:
#   - settings.nix : monitors, input, appearance (general/decoration/animations)
#   - binds.nix    : all keyboard and mouse shortcuts
#   - rules.nix    : windowrule / layerrule
#   - dms.nix      : DankMaterialShell integration (exec-once, colors, polkit)
#
# The system-level part (programs.hyprland, portals, DMS) lives in
# modules/system/desktop-environment/.
#
# This split is possible because the `settings` type is recursive
# (attrsOf/listOf): attrsets merge, lists concatenate. So `bind` can be
# defined in binds.nix and `general` in settings.nix without conflict.
{ config, lib, pkgs, ... }:

let
  cfg = config.myModules.hyprland;
in
{
  imports = [
    ./settings.nix
    ./binds.nix
    ./rules.nix
    ./dms.nix
  ];

  options.myModules.hyprland = {
    enable = lib.mkEnableOption "Hyprland (user configuration)";

    keyboardLayout = lib.mkOption {
      type = lib.types.str;
      default = "fr";
      description = "Value of input.kb_layout.";
    };

    terminal = lib.mkOption {
      type = lib.types.str;
      default = "ghostty";
      description = ''
        Command launched by $mod + RETURN.
      '';
    };

    fileManager = lib.mkOption {
      type = lib.types.str;
      default = "nautilus";
      description = ''
        Command launched by $mod + E.
        The package is installed further below.
      '';
    };

    workspaceCount = lib.mkOption {
      type = lib.types.ints.between 1 10;
      default = 3;
      description = ''
        Number of workspaces bound to $mod + <n>.
        The generated binds use code:10..code:19, i.e. the *physical*
        1..0 keys: on AZERTY the keysyms are &, é, " ... so a bind
        written as "$mod, 1" would never trigger.
      '';
    };

    dms.enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        DankMaterialShell integration: exec-once `dms run`, IPC binds,
        sourcing of the color file generated by matugen.
        Assumes myModules.desktopEnvironment.dms.enable on the system side.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;

      # Deliberately false: see the exec-once comment in dms.nix.
      systemd.enable = false;
    };

    home.packages = [
      pkgs.nautilus # see the fileManager option
    ];

    # No `gtk = { ... }` block here, deliberately: DMS writes the GTK theme
    # dynamically to ~/.config/gtk-{3,4}.0/ via matugen. If Home Manager
    # places symlinks there pointing to the (read-only) store, matugen fails
    # and Nautilus stays gray. Theme, icons and font are set in DMS ($mod + S).
  };
}
