# modules/home-manager/hyprland/dms.nix
#
# User-side DankMaterialShell integration.
# DMS itself (package, plugins, dependencies) is enabled on the system side:
#   myModules.desktopEnvironment.dms.enable
{ config, lib, pkgs, ... }:

let
  cfg = config.myModules.hyprland;
in
{
  config = lib.mkIf (cfg.enable && cfg.dms.enable) {
    wayland.windowManager.hyprland = {
      settings.exec-once = [
        # Without this, user services (tray, portals, polkit agent) start
        # with an empty environment: they see neither WAYLAND_DISPLAY nor
        # HYPRLAND_INSTANCE_SIGNATURE and fail silently.
        "dbus-update-activation-environment --systemd --all"

        # The unit exists (services.hyprpolkitagent below) but its
        # WantedBy points to graphical-session.target, never reached here:
        # so it's started manually.
        "systemctl --user start hyprpolkitagent"

        # `dms run` rather than dms.service, for the same reason: with
        # systemd.enable = false, a service attached to graphical-session.target
        # would stay stuck waiting indefinitely.
        "dms run"
      ];

      # Colors regenerated by matugen on every wallpaper change.
      # The file must exist before Hyprland's first launch:
      # `dms setup colors` creates it if needed. Hyprland refuses to start on
      # a `source` pointing to a missing file.
      extraConfig = ''
        source = ~/.config/hypr/dms/colors.conf
      '';
    };

    # Installs both the package AND the systemd user unit. Putting only
    # pkgs.hyprpolkitagent in home.packages isn't enough: the unit wouldn't
    # be visible to `systemctl --user`, and the exec-once above would fail.
    services.hyprpolkitagent.enable = true;

    home.packages = [
      pkgs.wl-clipboard # required by DMS's clipboard history
    ];
  };
}
