#!/usr/sbin/nft -f

flush ruleset

table inet firewall {
        set authorized_public_ipv4 {
        type ipv4_addr
        elements = {
            X.X.X.X, # IP1
            Y.Y.Y.Y, # IP2
        }
    }
        chain input {
                type filter hook input priority 0;
                policy drop;

                # Loopback interface restrictions
                iif lo accept
                iif != lo ip daddr 127.0.0.1/8 counter drop comment "Drop connections to loopback not coming from loopback"
                iif != lo ip6 daddr ::1/128 counter drop comment "Drop connections to loopback not coming from loopback"

                # ICMP Restrictions
                icmp type echo-request limit rate 5/second accept
                icmpv6 type { nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert } accept
                icmpv6 type echo-request limit rate 5/second accept

                # Accept established connections
                ct state vmap { established : accept, related : drop, invalid : drop }

                # Allow SSH only from specific IPs
                ip saddr @authorized_public_ipv4 tcp dport 22 ct state new accept
        }
        chain forward {
                type filter hook forward priority filter;
                policy accept;
        }
        chain output {
                type filter hook output priority filter;
                policy accept;
        }
}
